### ISSUE TITLE
Is there any way to print to a preselected printer without showing dialog box

### ISSUE THREAD

**Issue by nimaanu** [EddyVerbruggen/nativescript-printer#20]

**Comment by EddyVerbruggen** [comment]
Dude, you asked the same at #18

**Comment by nimaanu** [comment]
Ok, sorry for the repeated question actualy i didnt't seen you reply #18,
nativescript star printer plugin supports only bluetooth printer i think,
am using wi fi printer brother QL720NW
,  I stuck by some  more issues like Printing page orientation, print
preview shows printing item in landscape mode but prints in portrait mode,
can you plz help
Thanks for you reply
