### ISSUE TITLE
Cannot read property 'getApplicationContext' of undefined

### ISSUE THREAD

**Issue by Mauoanel** [EddyVerbruggen/nativescript-printer#30]
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getApplicationContext' of undefined
JS: TypeError: Cannot read property 'getApplicationContext' of undefined
JS:     at new Printer (file: node_modules/nativescript-printer/printer.android.js:8:33)
JS:     at new HomeComponent (file: src/app/home/home.component.ts:53:24)
JS:     at createClass (file: node_modules/@angular/core/fesm5/core.js:21158:0)
JS:     at createDirectiveInstance (file: node_modules/@angular/core/fesm5/core.js:21027:0)
JS:     at createViewNodes (file: node_modules/@angular/core/fesm5/core.js:29387:0)
JS:     at createRootView (file: node_modules/@angular/core/fesm5/core.js:29301:0)
JS:     at callWithDebugContext (file: node_modules/@angular/core/fesm5/core.js:30309:0)
JS:     at Object.debugCreateRootView [as createRootView] (file: node_modules/@angular/core/fesm5/core.js:29819:0)
JS:     at ComponentFactory_.push.../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create

**Comment by Mauoanel** [comment]
hi everyone, do any of you know as to why android throws the below error message?
TypeError: Cannot read property 'getApplicationContext' of undefined

**Comment by asharghi** [comment]
Getting the same on Android. iOS works.
